# LEETCODE 389

'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
'''

def findTheDifference(s, t):
    result = 0
    for char in s + t:
        result ^= ord(char)
    return chr(result)

# Alternate solution

def findTheDifferenceAlt(s, t):
    return chr(sum(ord(char) for char in t) - sum(ord(char) for char in s))

# Example usage
s1 = "abcd"
t1 = "abcde"
print(findTheDifference(s1, t1))  # Output: 'e'

# Additional examples
s2 = "xyz"
t2 = "xyza"
print(findTheDifference(s2, t2))  # Output: 'a'

s3 = "hello"
t3 = "ohelloz"
print(findTheDifference(s3, t3))  # Output: 'z'

s4 = "test"
t4 = "ttest"
print(findTheDifference(s4, t4))  # Output: 't'

s5 = "a"
t5 = "aa"
print(findTheDifference(s5, t5))  # Output: 'a'